# Generated by Django 3.0.1 on 2021-02-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centidevNew', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TCentipanelMenu',
            new_name='TCentipanelMenuNew',
        ),
    ]
