# Generated by Django 3.0.1 on 2021-02-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centidevNew', '0002_auto_20210215_1535'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TCentipanelMenuNew',
            new_name='Report',
        ),
    ]
