# Generated by Django 3.0.1 on 2021-02-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centidev', '0002_auto_20210201_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False, 'ordering': ('-published',)},
        ),
    ]
