# Generated by Django 3.0.1 on 2021-02-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centidev', '0003_auto_20210208_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published',)},
        ),
    ]
