# Generated by Django 3.0.1 on 2021-02-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centidev', '0004_auto_20210208_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='co_codigo',
            field=models.CharField(blank=True, db_column='Co_Codigo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_database',
            field=models.CharField(blank=True, db_column='CO_DATABASE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_empresa',
            field=models.CharField(blank=True, db_column='Co_Empresa', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_estatus',
            field=models.CharField(blank=True, db_column='Co_Estatus', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_existe_modulo',
            field=models.CharField(blank=True, db_column='CO_EXISTE_MODULO', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_grupo',
            field=models.CharField(blank=True, db_column='CO_GRUPO', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_lista',
            field=models.CharField(blank=True, db_column='CO_LISTA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_main',
            field=models.CharField(blank=True, db_column='CO_MAIN', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_modulo',
            field=models.CharField(blank=True, db_column='CO_MODULO', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_opcion',
            field=models.CharField(blank=True, db_column='CO_OPCION', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_output',
            field=models.CharField(blank=True, db_column='CO_OUTPUT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_search',
            field=models.CharField(blank=True, db_column='CO_SEARCH', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_tabla',
            field=models.CharField(blank=True, db_column='CO_TABLA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_tabla_nueva',
            field=models.CharField(blank=True, db_column='CO_TABLA_NUEVA', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_tabla_temporal',
            field=models.CharField(blank=True, db_column='CO_TABLA_TEMPORAL', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_usuario',
            field=models.CharField(blank=True, db_column='Co_Usuario', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='co_visible',
            field=models.CharField(blank=True, db_column='CO_VISIBLE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fe_update',
            field=models.CharField(blank=True, db_column='Fe_Update', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nb_modulo_no',
            field=models.CharField(blank=True, db_column='NB_MODULO_NO', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nb_modulo_si',
            field=models.CharField(blank=True, db_column='NB_MODULO_SI', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nb_opcion',
            field=models.CharField(blank=True, db_column='NB_OPCION', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nb_search',
            field=models.CharField(blank=True, db_column='NB_SEARCH', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nb_tabla_centipede',
            field=models.CharField(blank=True, db_column='NB_TABLA_CENTIPEDE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nu_orden',
            field=models.FloatField(blank=True, db_column='NU_ORDEN', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='nu_orden_opcion',
            field=models.FloatField(blank=True, db_column='NU_ORDEN_OPCION', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tx_marca_empresa',
            field=models.CharField(blank=True, db_column='Tx_Marca_Empresa', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tx_prefijo_export',
            field=models.CharField(blank=True, db_column='TX_PREFIJO_EXPORT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tx_procedure',
            field=models.CharField(blank=True, db_column='Tx_PROCEDURE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tx_query',
            field=models.CharField(blank=True, db_column='Tx_QUERY', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tx_tipo_opcion',
            field=models.CharField(blank=True, db_column='TX_TIPO_OPCION', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tx_tipo_search',
            field=models.CharField(blank=True, db_column='TX_TIPO_SEARCH', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tx_type_output',
            field=models.CharField(blank=True, db_column='TX_TYPE_OUTPUT', max_length=50, null=True),
        ),
    ]
